version: '3.9'

name: microservice-cinema

services:
  notification-service:
    container_name: notification-service
    image: microservice-cinema/notification-service:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production.local
    expose:
      - '9102'
    networks:
      - microservice-cinema

networks:
  microservice-cinema:
    external: true